spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/localdb
    username: postgres
    password: hello1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
